### ISSUE TITLE
Add a gif to the README

### ISSUE THREAD

**Issue by palash25** [knrt10/IssueTracker#1]
Readme looks cluttered with all those screenshots. Replace them with a GIF.

**Comment by knrt10** [comment]
# Issue Tracker

An Issue Tracker Bot allowing you to create issues easily and prevent creating any duplicate issues.

## Working (Gif)

<img src="http://res.cloudinary.com/dsyvg5xwi/image/upload/v1518845574/Peek_2018-02-17_11-01_tywloy.gif"/>

## How does it Work (Screenshots).

1. Initial State of Open issues

<img src="http://res.cloudinary.com/dsyvg5xwi/image/upload/v1518843898/Initialissues_icculu.png"/>

2. Creating a sort of similar Issue.

<img src="http://res.cloudinary.com/dsyvg5xwi/image/upload/v1518844155/issuesimlar_kmxkgn.png"/>

3. Result when you create similar Issue.

<img src="http://res.cloudinary.com/dsyvg5xwi/image/upload/v1518844224/issuesimalrresult_ib6vwi.png"/>

4. Now creating Different issue.

<img src="http://res.cloudinary.com/dsyvg5xwi/image/upload/v1518844231/issuenotsim_rcaens.png"/>

5. Result when issue is not similar

<img src="http://res.cloudinary.com/dsyvg5xwi/image/upload/v1518844237/issuenotsimres_wj4frd.png"/>

## How to Use.

1. Visit <a href="https://github.com/apps/issuetrack">Here</a>.

2. Install the github app and configue it for all repositories.

3. Now when ever you create an issue in the repositoriesin which you have allowed configuration of app, issues will be checked automatically and it will prevent you from creating any duplicate issue.
